# Generated by Django 4.2.14 on 2024-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50, null=True)),
                ('printCompanyName', models.CharField(max_length=50, null=True)),
                ('address1', models.CharField(max_length=50, null=True)),
                ('address2', models.CharField(max_length=50, null=True)),
                ('address3', models.CharField(max_length=50, null=True)),
                ('address4', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('gstRegType', models.CharField(max_length=50, null=True)),
                ('salesEntry', models.CharField(max_length=50, null=True)),
                ('saleInclusive', models.CharField(max_length=50, null=True)),
                ('blankSaleItems', models.CharField(max_length=50, null=True)),
                ('makeRoundOff', models.CharField(max_length=50, null=True)),
                ('showDiscount', models.CharField(max_length=50, null=True)),
                ('showGstDetails', models.CharField(max_length=50, null=True)),
                ('gstIn', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50, null=True)),
                ('companyName', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('gstin', models.CharField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('gstRegType', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=50, null=True)),
                ('itemName', models.CharField(max_length=50, null=True)),
                ('hsnCode', models.CharField(max_length=50, null=True)),
                ('uom', models.CharField(max_length=50, null=True)),
                ('isGoodOrService', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('ratePerUnit', models.CharField(max_length=50, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('totalGstPercent', models.CharField(max_length=50, null=True)),
                ('sgstPercent', models.CharField(max_length=50, null=True)),
                ('cgstPercent', models.CharField(max_length=50, null=True)),
                ('igstPercent', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50, null=True)),
                ('companyName', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=100)),
                ('gstRegType', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('itemName', models.CharField(max_length=100)),
                ('hsnCode', models.CharField(max_length=100)),
                ('ratePerUnit', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('totalGstPercent', models.CharField(max_length=100)),
                ('sgstPercent', models.CharField(max_length=100)),
                ('cgstPercent', models.CharField(max_length=100)),
                ('igstPercent', models.CharField(max_length=100)),
                ('quot_Number', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
